apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testing
spec:
   generators:
    - git:
        repoURL: https://github.com/PC-1119/dummy1
        revision: main
        directory:
          path: dev/*
          recurse: false
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/PC-1119/dummy1
        targetRevision: main
        path: 'dev/{{path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
