apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wannatestargocd
spec:
  generators:
  - git:
      repoURL: https://github.com/PC-1119/dummy1
      revision: main
      directories:
      - path: dev/*
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/PC-1119/dummy1
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
